# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/analytics2',
                'doc_host': 'https://scmopt.github.io',
                'git_url': 'https://github.com/scmopt/analytics2',
                'lib_path': 'analytics2'},
  'syms': { 'analytics2.core': {'analytics2.core.foo': ('core.html#foo', 'analytics2/core.py')},
            'analytics2.fastai': {},
            'analytics2.networkx': {},
            'analytics2.neuralprophetf': {}}}