# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/16fastai.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/16fastai.ipynb 3
import pandas as pd
from sklearn.model_selection import train_test_split
from fastai.tabular.all import *
