# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/17neuralprophet.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/17neuralprophet.ipynb 7
import pandas as pd
from neuralprophet import NeuralProphet, set_log_level

# エラー以外はログメッセージを抑制
set_log_level("ERROR")

from vega_datasets import data
import plotly.express as px
import plotly
