[tool.poetry]
name = "analytics2"
version = "0.1.0"
description = ""
authors = ["mikio kubo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
